name: build Custom

on:
    workflow_dispatch:
      inputs:
        KSU:
          required: true
          type: choice
          description: "选择KSU变体"
          default: "RKSU"
          options:
            - 'KSU'
            - 'SUKISU'
            - 'NEXT'
            - 'WILD'
            - 'RKSU'
            - 'YCRKSU'
            - 'XXKSU'
        BBG:
          type: boolean
          description: "启用 BBG"
          default: false
        SUSFS:
          type: boolean
          description: "启用 SUSFS"
          default: false
        mountify:
          type: boolean
          description: "启用 Mountify 模块支持"
          default: false
jobs:
  Build-Kernel:
    name: "Build kernel normal"
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CCACHE_DIR: /home/runner/.ccache  
      CCACHE_MAXSIZE: 8G
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Restore ccache
        uses: actions/cache@v3
        with:
          path: /home/runner/.ccache
          key: ccache-${{ runner.os }}-${{ github.event.inputs.KSU }}-${{ github.ref }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ github.event.inputs.KSU }}-

      - name: Set git config
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ github.actor }}@users.noreply.github.com

      - name: Install repo tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: sync
        run: |
          mkdir kernel_workspace && cd kernel_workspace
          repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8750 -m oneplus_ace_6.xml --depth=1
          repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync
          rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
          rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
          sed -i 's/ -dirty//g' kernel_platform/common/scripts/setlocalversion
          sed -i 's/ -dirty//g' kernel_platform/msm-kernel/scripts/setlocalversion
          sed -i 's/ -dirty//g' kernel_platform/external/dtc/scripts/setlocalversion
          sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' kernel_platform/common/scripts/setlocalversion
          sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' kernel_platform/msm-kernel/scripts/setlocalversion
          sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' kernel_platform/external/dtc/scripts/setlocalversion
          sed -i '$s|echo "\$res"|echo "-ogki-${{github.actor}}"|' kernel_platform/common/scripts/setlocalversion
          sed -i '$s|echo "\$res"|echo "-ogki-${{github.actor}}"|' kernel_platform/msm-kernel/scripts/setlocalversion
          sed -i '$s|echo "\$res"|echo "-ogki-${{github.actor}}"|' kernel_platform/external/dtc/scripts/setlocalversion

      - name: Get scripts
        uses: actions/checkout@v4
        with: 
          path: scripts

      - name: Run configure
        run: |
          cp ./scripts/scripts/configure ./kernel_workspace/
          chmod +x ./kernel_workspace/configure
          
          ARGS="--ksu-variant ${{ github.event.inputs.KSU }}"
          if [ "${{ github.event.inputs.SUSFS }}" == "true" ]; then
            ARGS+=" --susfs"
          fi
          if [ "${{ github.event.inputs.BBG }}" == "true" ]; then
            ARGS+=" --with-bbg"
          fi
          if [ "${{ github.event.inputs.mountify }}" == "true" ]; then
            ARGS+=" --mountify"
          fi
          cd kernel_workspace
          ./configure $ARGS

      - name: build
        run: |
          export PATH="/usr/lib/ccache:$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/prebuilts/clang/host/linux-x86/clang-r510928/bin:$PATH" 
          export PATH="/usr/lib/ccache:$PATH"
          sudo apt install libelf-dev ccache
          cd kernel_workspace/kernel_platform/common
          make -j$(nproc --all) LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC="ccache clang" RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole LD=ld.lld HOSTLD=ld.lld O=out KCFLAGS+=-O2  gki_defconfig all

      - name: Pack anykernel3
        run: |
         cd kernel_workspace/
         git clone https://github.com/luyancib-org/Anykernel3 --depth=1
         rm -rf Anykernel3/.git
         cp kernel_platform/common/out/arch/arm64/boot/Image.gz ./Anykernel3/Image.gz
         cd Anykernel3
         zip -q -r "../AnyKernel3_Op_ACE6.zip" ./*

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Anykernel3
          path: kernel_workspace/AnyKernel3_Op_ACE6.zip

      - name: Upload to telegram
        run: |
          if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
            pip3 install telethon
            python3 ./scripts/scripts/buildbot.py "./kernel_workspace/AnyKernel3_Op_ACE6.zip"
          fi
        env:
          CHATID: ${{secrets.CHATID}}
          BOT_TOKEN: ${{secrets.BOT_TOKEN}}
          MESSAGE_THREAD_ID: ${{secrets.MESSAGE_THREAD_ID}}
          KSUVAR: ${{ github.event.inputs.KSU }}
          SUSFS: ${{ github.event.inputs.SUSFS }}
          BBG: ${{ github.event.inputs.BBG }}
          mountify: ${{ github.event.inputs.mountify }}
         
         
